### ISSUE TITLE
How to finish the training process?

### ISSUE THREAD

**Issue by Danielll2** [TobyPDE/FRRN#12]
Is there any number of iteration of training?
or Just put Ctrl+C to stop training?

**Comment by TobyPDE** [comment]
I usually perform manual early stopping by watching the validation IoU score and terminating the training process via CTRL + C once it no longer improves.

**Comment by Danielll2** [comment]
Thanks a lot!

**Comment by TobyPDE** [comment]
Quick heads up: I'm currently working on significantly speeding up training by optimizing the block-backprop algorithm and porting some code to C++. I will publish the code within the next 1-2 weeks.
