### ISSUE TITLE
How to make model file

### ISSUE THREAD

**Issue by Danielll2** [TobyPDE/FRRN#13]
When I trained the model with new semantic DB, I used empty folders("logs" and "models") for train.py.
For finish training process, I put Ctrl+C. Logs folder has the files for log. But there are no files in models folder.
Should I use the exising models file and folder for training(models/frrn_b.npz)?
Does the train.py makes new model file?
Do I have to get any initial stuff before train?
thanks

**Comment by TobyPDE** [comment]
When being ask to provide a model file, simply point to a file that does not exist yet. Also the logging solution has been fixed. Now all logs are written to the same file. Please update your codebase by pulling the latest changes. 

Furthermore, a substantial update will be published within the next 2-3 weeks that will speed up training significantly.
