### ISSUE TITLE
Effect of Data Augmentation

### ISSUE THREAD

**Issue by playerkk** [TobyPDE/FRRN#17]
Hi, I was wondering how effective the data augmentation is. Particularly, I was wondering if you observed significant performance difference on the validation and testing set, if without using the data augmentation. Thanks.

**Comment by TobyPDE** [comment]
Data augmentation is exceptionally important if you train from scratch. At the moment, I'm even retraining the models with a more extensive data augmentation pipeline. I have already released the retrained FRRN A model. The FRRN B model will follow soon together with the updated code.

If you train without data augmentation, you will observe significantly lower IoU scores on the validation and test sets.
