### ISSUE TITLE
input image is black

### ISSUE THREAD

**Issue by manuel-88** [TobyPDE/FRRN#24]
Hey, I tested your framework with the cityscape dataset and the trained models (predict.py) but the output is very bad (losses between 100 - 500). I checked the output images(image, gt_img and pred_img) and saw that the RGB is just black. The gt is the same like from the dataset and the pred is a very bad segmented image. 

The paths to the cityscape seems to be right and the dependency check runs with no error.

Thank you for help.

**Comment by TobyPDE** [comment]
Can you make sure that the path to the model is correct? The code does not raise an error if the model file doesn't exist.

**Comment by manuel-88** [comment]
yes the model path was wrong. The segmentation works, thank you.

But why is the plotted image of the input still black?

**Comment by TobyPDE** [comment]
I'm not entirely sure. The image is a [0, 1] normalized floating point image. Maybe your installed version of OpenCV can't handle floating point images (I tested with OpenCV 3.x).
