### ISSUE TITLE
The questions about prediction

### ISSUE THREAD

**Issue by Youngkl0726** [TobyPDE/FRRN#27]
I tried to run FRRN using other pictures for prediction. But I had to change the names of pictures and the names had to be just like the pictures of Cityscapes. Can you offer a version that FRRN can predict all pictures without change the names of pictures?
I tried to change the code to realize this idea but the results were so bad that I doubted that there was something wrong with my code. Once I removed the "batch[1]" from the "val_fn" in prediction.py and, of course, correspondingly changed the code in train.py, the results changed and the results got bad.

**Comment by TobyPDE** [comment]
Hey, 
You can load any picture you want by giving a list of string tuples to the data provider. The comments should explain how it works in detail. Unfortunately, I don't have the capacity to implement new features anymore.
