### ISSUE TITLE
How to install theano and lasagne on python 3.5.1

### ISSUE THREAD

**Issue by gaopeng-eugene** [TobyPDE/FRRN#5]
Thank you so much for your open source code.

I run into problems when install theano and lasagne on python3.5.1.

First, I install python 3.5.1 from source code.
Then, I use pip3.5 install theano and lasagne.

Here is the error message
Problem occurred during compilation with the command line below:
/usr/bin/g++ -shared -g -march=core-avx2 -mcx16 -msahf -mmovbe -maes -mpclmul -mpopcnt -mabm -mno-lwp -mfma -mno-fma4 -mno-xop -mbmi -mbmi2 -mno-tbm -mavx -mavx2 -msse4.2 -msse4.1 -mlzcnt -mrtm -mhle -mrdrnd -mf16c -mfsgsbase -mrdseed -mprfchw -madx -mfxsr -mxsave -mxsaveopt --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=51200 -mtune=generic -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -I/usr/local/lib/python3.5/site-packages/numpy/core/include -I/usr/local/include/python3.5m -I/usr/local/lib/python3.5/site-packages/theano/gof -fvisibility=hidden -o /root/.theano/compiledir_Linux-4.2--generic-x86_64-with-debian-jessie-sid-x86_64-3.5.1-64/lazylinker_ext/lazylinker_ext.so /root/.theano/compiledir_Linux-4.2--generic-x86_64-with-debian-jessie-sid-x86_64-3.5.1-64/lazylinker_ext/mod.cpp -L/usr/local/lib -lpython3.5m
/usr/bin/ld: /usr/local/lib/libpython3.5m.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.5m.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status

Operating System :

Ubuntu 14

**Comment by TobyPDE** [comment]
The problem is that you don't have shared python libraries (they have the extension .so). Simply go back to your python build directory and run `./configure --enable-shared` followed by `make install`.

**Comment by gaopeng-eugene** [comment]
Thank you so much for your suggestion. Problem solved.
